### ISSUE TITLE
Remove default input styling on Safari

### ISSUE THREAD

**Issue by andreipfeiffer** [tim-js/revojs.ro#21]
![Image from iOS](https://user-images.githubusercontent.com/2570562/76087571-1c839880-5fbf-11ea-8345-311575829c81.png)

**Comment by andreipfeiffer** [comment]
@ionmosincat ai putea sa te uiti peste issue-ul asta?
Pe Safari, pe mobile cel putin, inputul este rotunjit by default, si arata aiurea borderul ala de jos.
Ar trebui scoase stilurile default de Safari/webkit.

**Comment by ionmosincat** [comment]
Ok, ma uit azi
